apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kishorerkv/argocd_demo   # your repo
    targetRevision: HEAD
    path: httpd-chart                                    # folder where Chart.yaml is
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
